import { mkdir, open, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import { randomUUID } from "node:crypto";
import type { BudgetRequest, Reservation, UsageActual, UsageLedger, UsageSnapshot } from "../../domain/ports/usage-ledger.js";
type State = { spent: number; reservations: Record<string, BudgetRequest> };
type Lock = { token: string; acquiredAt: number };
type LockOptions = { readonly staleLockMs?: number; readonly retryMs?: number; readonly maxAttempts?: number };
export class FileUsageLedger implements UsageLedger {
  private chain = Promise.resolve();
  constructor(private readonly file: string, private readonly budget: { readonly limit: number }, private readonly lockOptions: LockOptions = {}) {}
  private async state(): Promise<State> { let raw: string; try { raw = await readFile(this.file, "utf8"); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { spent: 0, reservations: {} }; throw new Error(`usage ledger state is unreadable: ${(error as Error).message}`); } let parsed: unknown; try { parsed = JSON.parse(raw); } catch { throw new Error("usage ledger state is corrupt; refusing to reset budget"); } if (!parsed || typeof parsed !== "object") throw new Error("usage ledger state is corrupt; refusing to reset budget"); const state = parsed as State; if (!Number.isFinite(state.spent) || state.spent < 0 || !state.reservations || typeof state.reservations !== "object" || Object.values(state.reservations).some((item) => !item || typeof item.operation !== "string" || !Number.isFinite(item.estimated) || item.estimated < 0)) throw new Error("usage ledger state is corrupt; refusing to reset budget"); return state; }
  private async releaseLock(lockPath: string, token: string): Promise<void> { try { const current = JSON.parse(await readFile(lockPath, "utf8")) as Lock; if (current.token === token) await unlink(lockPath); } catch { /* A concurrent/manual change leaves the lock intact rather than deleting another owner's lock. */ } }
  private async withLock<T>(fn: () => Promise<T>): Promise<T> { const lockPath = `${this.file}.lock`; const retryMs = this.lockOptions.retryMs ?? 10; const maxAttempts = this.lockOptions.maxAttempts ?? 100; const staleLockMs = this.lockOptions.staleLockMs ?? 60_000; for (let attempt = 0; attempt < maxAttempts; attempt += 1) { const token = randomUUID(); try { await mkdir(dirname(this.file), { recursive: true }); const handle = await open(lockPath, "wx"); try { await handle.writeFile(JSON.stringify({ token, acquiredAt: Date.now() })); await handle.sync(); } finally { await handle.close(); } try { return await fn(); } finally { await this.releaseLock(lockPath, token); } } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; try { const existing = JSON.parse(await readFile(lockPath, "utf8")) as Lock; if (typeof existing.token === "string" && Number.isFinite(existing.acquiredAt) && Date.now() - existing.acquiredAt > staleLockMs) throw new Error("usage ledger stale lock requires manual recovery"); } catch (lockError) { if (lockError instanceof Error && /stale lock/.test(lockError.message)) throw lockError; } await new Promise((resolve) => setTimeout(resolve, retryMs)); } } throw new Error("usage ledger lock timeout"); }
  private async mutate<T>(fn: (state: State) => T): Promise<T> { const next = this.chain.then(() => this.withLock(async () => { const state = await this.state(); const result = fn(state); const temp = `${this.file}.${randomUUID()}.tmp`; await writeFile(temp, JSON.stringify(state), "utf8"); await rename(temp, this.file); return result; })); this.chain = next.then(() => undefined, () => undefined); return next; }
  async reserve(request: BudgetRequest): Promise<Reservation> { if (request.estimated < 0) throw new Error("estimated usage must be non-negative"); return this.mutate((state) => { const reserved = Object.values(state.reservations).reduce((sum, item) => sum + item.estimated, 0); if (state.spent + reserved + request.estimated > this.budget.limit) throw new Error("budget exceeded before external call"); const id = randomUUID(); state.reservations[id] = request; return { id, request }; }); }
  async commit(id: string, actual: UsageActual): Promise<void> { await this.mutate((state) => { if (!Number.isFinite(actual.cost) || actual.cost < 0) throw new Error("actual usage must be finite and non-negative"); if (!state.reservations[id]) throw new Error(`unknown reservation ${id}`); const reservedElsewhere = Object.entries(state.reservations).filter(([key]) => key !== id).reduce((sum, [, item]) => sum + item.estimated, 0); if (state.spent + reservedElsewhere + actual.cost > this.budget.limit) throw new Error("budget exceeded while committing actual usage"); delete state.reservations[id]; state.spent += actual.cost; }); }
  async release(id: string, _reason: string): Promise<void> { await this.mutate((state) => { delete state.reservations[id]; }); }
  async snapshot(): Promise<UsageSnapshot> { return this.mutate((state) => ({ spent: state.spent, reserved: Object.values(state.reservations).reduce((sum, item) => sum + item.estimated, 0) })); }
}
