import { randomUUID } from "node:crypto";
import { mkdir, open, readFile, rename, unlink, writeFile } from "node:fs/promises";
import { dirname } from "node:path";
import type { BudgetRequest, Reservation, UsageCommit, UsageEstimate, UsageLedger, UsageResult, UsageSnapshot, UsageUnit } from "../../domain/ports/usage-ledger.js";

type StoredReservation = { readonly operation: string; readonly estimate: UsageEstimate };
type CacheStageMetrics = { hits: number; savings: number; spent: number };
type State = { unit: UsageUnit; spent: number; reservations: Record<string, StoredReservation>; cacheHits: number; cacheSavings: number; cacheByOperation: Record<string, CacheStageMetrics> };
type Lock = { token: string; acquiredAt: number };
type LockOptions = { readonly staleLockMs?: number; readonly retryMs?: number; readonly maxAttempts?: number };
const UNIT: UsageUnit = "usd-micros";
const assertAmount = (amount: number, label: string): void => { if (!Number.isSafeInteger(amount) || amount < 0) throw new Error(`${label} must be finite and non-negative safe integer`); };
function toEstimate(request: BudgetRequest): UsageEstimate { const estimate = request.estimate ?? (request.estimated === undefined ? undefined : { unit: UNIT, amount: request.estimated }); if (!estimate || estimate.unit !== UNIT) throw new Error("usage estimate must use usd-micros"); assertAmount(estimate.amount, "estimated usage"); return estimate; }
function toResult(actual: UsageCommit): UsageResult { if ("cost" in actual) { assertAmount(actual.cost, "actual usage"); return { unit: UNIT, amount: actual.cost, cache: actual.cached ? "hit" : "miss" }; } if (actual.unit !== UNIT) throw new Error("actual usage unit must match reservation unit usd-micros"); assertAmount(actual.amount, "actual usage"); return actual; }
function normalizeReservation(value: unknown): StoredReservation | null { if (!value || typeof value !== "object") return null; const item = value as { operation?: unknown; estimate?: UsageEstimate; estimated?: unknown }; const estimate = item.estimate ?? (typeof item.estimated === "number" ? { unit: UNIT, amount: item.estimated } : undefined); if (typeof item.operation !== "string" || !estimate || estimate.unit !== UNIT || !Number.isSafeInteger(estimate.amount) || estimate.amount < 0) return null; return { operation: item.operation, estimate }; }

export class FileUsageLedger implements UsageLedger {
  private chain = Promise.resolve();
  constructor(private readonly file: string, private readonly budget: { readonly limit: number }, private readonly lockOptions: LockOptions = {}) { assertAmount(budget.limit, "budget limit"); }
  private async state(): Promise<State> { let raw: string; try { raw = await readFile(this.file, "utf8"); } catch (error) { if ((error as NodeJS.ErrnoException).code === "ENOENT") return { unit: UNIT, spent: 0, reservations: {}, cacheHits: 0, cacheSavings: 0, cacheByOperation: {} }; throw new Error(`usage ledger state is unreadable: ${(error as Error).message}`); } let parsed: unknown; try { parsed = JSON.parse(raw); } catch { throw new Error("usage ledger state is corrupt; refusing to reset budget"); } if (!parsed || typeof parsed !== "object") throw new Error("usage ledger state is corrupt; refusing to reset budget"); const candidate = parsed as { unit?: unknown; spent?: unknown; reservations?: unknown; cacheHits?: unknown; cacheSavings?: unknown; cacheByOperation?: unknown }; const spent = candidate.spent; if (candidate.cacheHits !== undefined && (typeof candidate.cacheHits !== "number" || !Number.isSafeInteger(candidate.cacheHits) || candidate.cacheHits < 0)) throw new Error("usage ledger state is corrupt; refusing to reset budget"); if (candidate.cacheSavings !== undefined && (typeof candidate.cacheSavings !== "number" || !Number.isSafeInteger(candidate.cacheSavings) || candidate.cacheSavings < 0)) throw new Error("usage ledger state is corrupt; refusing to reset budget"); const cacheHits = candidate.cacheHits === undefined ? 0 : candidate.cacheHits as number; const cacheSavings = candidate.cacheSavings === undefined ? 0 : candidate.cacheSavings as number; const cacheByOperation = normalizeCacheByOperation(candidate.cacheByOperation); if (!cacheByOperation) throw new Error("usage ledger state is corrupt; refusing to reset budget"); if (candidate.unit !== undefined && candidate.unit !== UNIT || typeof spent !== "number" || !Number.isSafeInteger(spent) || spent < 0 || !candidate.reservations || typeof candidate.reservations !== "object") throw new Error("usage ledger state is corrupt; refusing to reset budget"); const reservations = Object.fromEntries(Object.entries(candidate.reservations).map(([id, value]) => [id, normalizeReservation(value)])); if (Object.values(reservations).some((value) => value === null)) throw new Error("usage ledger state is corrupt; refusing to reset budget"); return { unit: UNIT, spent, reservations: reservations as Record<string, StoredReservation>, cacheHits, cacheSavings, cacheByOperation }; }
  private async releaseLock(lockPath: string, token: string): Promise<void> { try { if ((JSON.parse(await readFile(lockPath, "utf8")) as Lock).token === token) await unlink(lockPath); } catch { /* Preserve another owner's lock. */ } }
  private async withLock<T>(fn: () => Promise<T>): Promise<T> { const lockPath = `${this.file}.lock`; const retryMs = this.lockOptions.retryMs ?? 10; const maxAttempts = this.lockOptions.maxAttempts ?? 100; const staleLockMs = this.lockOptions.staleLockMs ?? 60_000; for (let attempt = 0; attempt < maxAttempts; attempt += 1) { const token = randomUUID(); try { await mkdir(dirname(this.file), { recursive: true }); const handle = await open(lockPath, "wx"); try { await handle.writeFile(JSON.stringify({ token, acquiredAt: Date.now() })); await handle.sync(); } finally { await handle.close(); } try { return await fn(); } finally { await this.releaseLock(lockPath, token); } } catch (error) { if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error; try { const existing = JSON.parse(await readFile(lockPath, "utf8")) as Lock; if (typeof existing.token === "string" && Number.isFinite(existing.acquiredAt) && Date.now() - existing.acquiredAt > staleLockMs) throw new Error("usage ledger stale lock requires manual recovery"); } catch (lockError) { if (lockError instanceof Error && /stale lock/.test(lockError.message)) throw lockError; } await new Promise((resolve) => setTimeout(resolve, retryMs)); } } throw new Error("usage ledger lock timeout"); }
  private async mutate<T>(fn: (state: State) => T): Promise<T> { const next = this.chain.then(() => this.withLock(async () => { const state = await this.state(); const result = fn(state); const temp = `${this.file}.${randomUUID()}.tmp`; await writeFile(temp, JSON.stringify(state), "utf8"); await rename(temp, this.file); return result; })); this.chain = next.then(() => undefined, () => undefined); return next; }
  async reserve(request: BudgetRequest): Promise<Reservation> { const estimate = toEstimate(request); return this.mutate((state) => { const reserved = Object.values(state.reservations).reduce((sum, item) => sum + item.estimate.amount, 0); if (state.spent + reserved + estimate.amount > this.budget.limit) throw new Error("budget exceeded before external call"); const id = randomUUID(); state.reservations[id] = { operation: request.operation, estimate }; return { id, request: { operation: request.operation, estimate } }; }); }
  async commit(id: string, actual: UsageCommit): Promise<void> { const result = toResult(actual); await this.mutate((state) => { const reservation = state.reservations[id]; if (!reservation) throw new Error(`unknown reservation ${id}`); const reservedElsewhere = Object.entries(state.reservations).filter(([key]) => key !== id).reduce((sum, [, item]) => sum + item.estimate.amount, 0); if (state.spent + reservedElsewhere + result.amount > this.budget.limit) throw new Error("budget exceeded while committing actual usage"); delete state.reservations[id]; state.spent += result.amount; const stage = state.cacheByOperation[reservation.operation] ?? { hits: 0, savings: 0, spent: 0 }; stage.spent += result.amount; if (result.cache === "hit") { const avoidedAmount = result.avoidedAmount ?? 0; assertAmount(avoidedAmount, "cache savings"); state.cacheHits += 1; state.cacheSavings += avoidedAmount; stage.hits += 1; stage.savings += avoidedAmount; } state.cacheByOperation[reservation.operation] = stage; }); }
  async release(id: string, _reason: string): Promise<void> { await this.mutate((state) => { delete state.reservations[id]; }); }
  async snapshot(): Promise<UsageSnapshot> { return this.mutate((state) => ({ spent: state.spent, reserved: Object.values(state.reservations).reduce((sum, item) => sum + item.estimate.amount, 0), unit: UNIT, ...(Object.keys(state.cacheByOperation).length === 0 ? {} : { cacheHits: state.cacheHits, cacheSavings: state.cacheSavings, cacheByOperation: state.cacheByOperation }) })); }
}

function normalizeCacheByOperation(value: unknown): Record<string, CacheStageMetrics> | null {
  if (value === undefined) return {};
  if (!value || typeof value !== "object") return null;
  const entries = Object.entries(value).map(([operation, metric]) => {
    if (!metric || typeof metric !== "object") return null;
    const { hits, savings, spent } = metric as Partial<CacheStageMetrics>;
    return typeof hits === "number" && Number.isSafeInteger(hits) && hits >= 0 && typeof savings === "number" && Number.isSafeInteger(savings) && savings >= 0 && (spent === undefined || typeof spent === "number" && Number.isSafeInteger(spent) && spent >= 0) ? [operation, { hits, savings, spent: spent ?? 0 }] as const : null;
  });
  return entries.some((entry) => entry === null) ? null : Object.fromEntries(entries as [string, CacheStageMetrics][]);
}
